### ISSUE TITLE
LES multirate upper boundary issue

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimateMachine.jl#1047] opened 2020-05-04 18:16 UTC
# Description
DYCOMS/BOMEX @smarras79 

## Steps to reproduce

1. Output of `git log -1`. In the case of bugs from code that has significantly diverged from master, a separate branch can be created and linked.
2. Exact sequence of commands run (REPL, terminal, or script) to reproduce this issue issue. 
3. Expected runtime for issue/bug to reveal itself (particularly useful in the case of problems with physics / set-ups that require longer time to solution)

## Screenshots

If applicable, add screenshots to help explain your problem, otherwise please remove this section. This can be particularly useful for physical simulations.

## Environment and error messages

 - Backtrace of error message
 - Include output of `julia> versioninfo()`

## Additional context

# For CLIMA developers

- [ ] The bug can be reproduced
- [ ] Labels have been added and developers assigned
- [ ] The bug can be fixed (if not, please explain why not in a comment below)
- [ ] There is a timeline to fix the bug
- [ ] The bug has been fixed (Please link the PR)

**Comment by smarras79** [comment] 2020-05-04 20:00
@simonbyrne The instructions follow. Thanks for taking a look.

1. Output of git log -1. In the case of bugs from code that has significantly diverged from master, a separate branch can be created and linked:

new branch right off master: 

```
commit 17054603da29d81cbb9723d32d7aed45db38a2f5 (HEAD -> sm/MR-top-boundary-tests, origin/sm/MR-top-boundary-tests)
Author: smarras79 <smarras@njit.edu>
Date:   Mon May 4 15:32:58 2020 -0400

    Added: experiments/AtmosLES/dycoms-full-run-MR.jl
```

[Link to branch](https://github.com/climate-machine/CLIMA/blob/sm/MR-top-boundary-tests/experiments/AtmosLES/dycoms-full-run-MR.jl)


2. Exact sequence of commands run (REPL, terminal, or script) to reproduce this issue issue.

`export outdir=YOUR_OUTPUT_DIR`

`julia --project ./experiments/AtmosLES/dycoms-full-run-MR.jl --diagnostics 200ssecs --output-dir $outdir`

3. Expected runtime for issue/bug to reveal itself (particularly useful in the case of problems with physics / set-ups that require longer time to solution)

The issue is already visible within the first 600 hundreds seconds of simulated time. 
The plot below shows you what what you will see (blue curve) versus what you should expect (dashed red curve). 
Although you will see the issues very early by observing the noisy curve, if you let the simulation run all the way, you will notice a drastic Th_l increase at the top boundary and a reduction of the underlying noise. I would recommend running your test at least to 3000 siumulated secons, which takes approximately 8 minutes of wall clock.

<img width="556" alt="MR-WRONG-THL-later-time" src="https://user-images.githubusercontent.com/46322845/81008088-4ec74000-8e20-11ea-9bef-5cb9e84a4f23.png">

**Comment by smarras79** [comment] 2020-05-04 21:08
@simonbyrne I can provide my matlab function ready to plot the NC files without having to do anything. Let me know if you'd like it.

**Comment by bischtob** [comment] 2020-05-05 00:22
@simonbyrne , @smarras79, does this impact 1D-IMEX and Held-Suarez as well? If so, can we add it to the list of experiments that need investigation?

**Comment by jkozdon** [comment] 2020-05-05 02:22
> @simonbyrne I can provide my matlab function ready to plot the NC files without having to do anything. Let me know if you'd like it.

If what you are asking is how can the plot be produced, the answer is yes this could be useful.

**Comment by smarras79** [comment] 2020-05-05 13:06
[PLOT_NCDF_SIMON.m.zip](https://github.com/climate-machine/ClimateMachine.jl/files/4580881/PLOT_NCDF_SIMON.m.zip)

**Comment by smarras79** [comment] 2020-05-05 13:08
> @simonbyrne , @smarras79, does this impact 1D-IMEX and Held-Suarez as well? If so, can we add it to the list of experiments that need investigation?

@bischtob from the comparison between 1D IMEX and MR that @szy21 ran yesterday for bomex, the issue seems to only be occurring with MR.

**Comment by bischtob** [comment] 2020-05-05 15:38
> > @simonbyrne , @smarras79, does this impact 1D-IMEX and Held-Suarez as well? If so, can we add it to the list of experiments that need investigation?
> 
> @bischtob from the comparison between 1D IMEX and MR that @szy21 ran yesterday for bomex, the issue seems to only be occurring with MR.

Thanks for letting me know.

**Comment by jkozdon** [comment] 2020-05-05 22:43
I've been doing a bit of testing of this and I do not think that this will be fixed by what I am currently working on with the remainder model (see #1037).

One thing I did notice is that the problem gets better with a smaller Courant number, at least in the early simulation time (I did not run the simulation to completion).

My guess is that there is something that should be applied in the fast solver that is currently not being applied (source, boundary condition, filter, etc.).

It could be useful if a very minimal example (minimal number of sources and simple boundary conditions) could be generated to display the issue.

**Comment by akshaysridhar** [comment] 2020-05-06 18:29
A comparison with the BOMEX case (`Float64` `master` vs `Float32` `master`) suggests some top-of-domain oscillations in the potential temperature plots (same metric as shown above for the DYCOMS simulation) when using `Float32` . So far I have **not** been able to track down anything that suggests this is related to the way **boundary conditions** are specified in the `AtmosModel` or applied in the `experiment`. I'll keep digging. If this has something to do with the float-type it's likely to produce similar results for the IMEX scheme (running these tests now). 
<img width="767" alt="Float64-BOMEX-MRRK" src="https://user-images.githubusercontent.com/43710045/81214284-7b986600-8f8c-11ea-8753-6971887330ad.png">
<img width="753" alt="Float32-BOMEX-MRRK" src="https://user-images.githubusercontent.com/43710045/81214298-80f5b080-8f8c-11ea-8949-f680150bfb7c.png">

**Comment by akshaysridhar** [comment] 2020-05-06 18:35
Running the DYCOMS from the master branch (basically to reproduce the error in the issue) shows the following. 
<img width="600" alt="Screen Shot 2020-05-06 at 11 31 08 AM" src="https://user-images.githubusercontent.com/43710045/81214705-16914000-8f8d-11ea-9fa9-b3475b1253f8.png">
Same oscillation at top-of-domain, `master` mode as-is on the left, and with adjusted saturation adjustment parameters and lower CFL (consistent with Jeremy's point above) (5 iteration maximum, 2K tolerance, with a CFL of 10)

**Closed** 2020-05-21 22:56 UTC
Labels: bug
